import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "QIAM-API/qiam-admin-rest-api",
    },
    {
      type: "category",
      label: "Attack Detection",
      link: {
        type: "doc",
        id: "QIAM-API/attack-detection",
      },
      items: [
        {
          type: "doc",
          id: "QIAM-API/delete-users",
          label: "deleteUsers",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-brute-force-user",
          label: "getBruteForceUser",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-brute-force-user",
          label: "deleteBruteForceUser",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Authentication Management",
      link: {
        type: "doc",
        id: "QIAM-API/authentication-management",
      },
      items: [
        {
          type: "doc",
          id: "QIAM-API/get-authenticator-providers",
          label: "getAuthenticatorProviders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-authenticator-providers",
          label: "getClientAuthenticatorProviders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-authentication-config",
          label: "postAuthenticationConfig",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/get-config-description",
          label: "getConfigDescription",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-authentication-config",
          label: "getAuthenticationConfig",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-authentication-config",
          label: "putAuthenticationConfig",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-config",
          label: "deleteConfig",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/post-executions",
          label: "postExecutions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/get-execution",
          label: "getExecution",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-execution",
          label: "deleteExecution",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/post-execution-config",
          label: "postExecutionConfig",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/get-execution-config",
          label: "getExecutionConfig",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-execution-lower-priority",
          label: "postExecutionLowerPriority",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/post-execution-raise-priority",
          label: "postExecutionRaisePriority",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/get-flows",
          label: "getFlows",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-flows",
          label: "postFlows",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/post-copy",
          label: "postCopy",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/get-executions",
          label: "getExecutions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-executions",
          label: "putExecutions",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/post-execution",
          label: "postExecution",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/post-flow",
          label: "postFlow",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/get-flow",
          label: "getFlow",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-flow",
          label: "putFlow",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-flow",
          label: "deleteFlow",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-form-action-providers",
          label: "getFormActionProviders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-form-providers",
          label: "getFormProviders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-per-client-config-description",
          label: "getPerClientConfigDescription",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-register-required-action",
          label: "postRegisterRequiredAction",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/get-required-actions",
          label: "getRequiredActions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-required-action",
          label: "getRequiredAction",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-required-action",
          label: "putRequiredAction",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-required-action",
          label: "deleteRequiredAction",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/post-required-action-lower-priority",
          label: "postRequiredActionLowerPriority",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/post-required-action-raise-priority",
          label: "postRequiredActionRaisePriority",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/get-unregistered-required-actions",
          label: "getUnregisteredRequiredActions",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Client Attribute Certificate",
      link: {
        type: "doc",
        id: "QIAM-API/client-attribute-certificate",
      },
      items: [
        {
          type: "doc",
          id: "QIAM-API/get-certificate",
          label: "getCertificate",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-download",
          label: "postDownload",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/post-generate",
          label: "postGenerate",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/post-generate-and-download",
          label: "postGenerateAndDownload",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/post-upload",
          label: "postUpload",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/post-upload-certificate",
          label: "postUploadCertificate",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Client Initial Access",
      link: {
        type: "doc",
        id: "QIAM-API/client-initial-access",
      },
      items: [
        {
          type: "doc",
          id: "QIAM-API/get-clients-initial-access",
          label: "getClientsInitialAccess",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-clients-initial-access",
          label: "postClientsInitialAccess",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-clients-initial-acces",
          label: "deleteClientsInitialAcces",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Client Registration Policy",
      link: {
        type: "doc",
        id: "QIAM-API/client-registration-policy",
      },
      items: [
        {
          type: "doc",
          id: "QIAM-API/get-providers",
          label: "getProviders",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Client Role Mappings",
      link: {
        type: "doc",
        id: "QIAM-API/client-role-mappings",
      },
      items: [
        {
          type: "doc",
          id: "QIAM-API/get-group-role-mappings-client",
          label: "getGroupRoleMappingsClient",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-group-role-mappings-client",
          label: "postGroupRoleMappingsClient",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-group-role-mappings-client",
          label: "deleteGroupRoleMappingsClient",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-group-role-mappings-client-available",
          label: "getGroupRoleMappingsClientAvailable",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-group-role-mappings-client-composite",
          label: "getGroupRoleMappingsClientComposite",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-user-role-mappings-client",
          label: "getUserRoleMappingsClient",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-user-role-mappings-client",
          label: "postUserRoleMappingsClient",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-user-role-mappings-client",
          label: "deleteUserRoleMappingsClient",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-user-role-mappings-client-available",
          label: "getUserRoleMappingsClientAvailable",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-user-role-mappings-client-composite",
          label: "getUserRoleMappingsClientComposite",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Client Scopes",
      link: {
        type: "doc",
        id: "QIAM-API/client-scopes",
      },
      items: [
        {
          type: "doc",
          id: "QIAM-API/get-client-scopes",
          label: "getClientScopes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-client-scopes",
          label: "postClientScopes",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-scope",
          label: "getClientScope",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-client-scope",
          label: "putClientScope",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-client-scope",
          label: "deleteClientScope",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-templates",
          label: "getClientTemplates",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-client-templates",
          label: "postClientTemplates",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-template",
          label: "getClientTemplate",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-client-template",
          label: "putClientTemplate",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-client-template",
          label: "deleteClientTemplate",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Clients",
      link: {
        type: "doc",
        id: "QIAM-API/clients",
      },
      items: [
        {
          type: "doc",
          id: "QIAM-API/get-clients",
          label: "getClients",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-clients",
          label: "postClients",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-by-realm-by-id",
          label: "getClientByRealmById",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-client",
          label: "putClient",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-client-by-realm-by-id",
          label: "deleteClientByRealmById",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-secret",
          label: "getClientSecret",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-client-secret",
          label: "postClientSecret",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/get-rotated",
          label: "getRotated",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-rotated",
          label: "deleteRotated",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-default-client-scopes",
          label: "getDefaultClientScopes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-default-client-scope",
          label: "putDefaultClientScope",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-default-client-scope",
          label: "deleteDefaultClientScope",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-generate-example-access-token",
          label: "getGenerateExampleAccessToken",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-generate-example-id-token",
          label: "getGenerateExampleIdToken",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-generate-example-userinfo",
          label: "getGenerateExampleUserinfo",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-protocol-mappers",
          label: "getProtocolMappers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-granted",
          label: "getGranted",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-not-granted",
          label: "getNotGranted",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-installation-provider",
          label: "getInstallationProvider",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-management-permissions",
          label: "getClientManagementPermissions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-client-management-permissions",
          label: "putClientManagementPermissions",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/post-nodes",
          label: "postNodes",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-node",
          label: "deleteNode",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-offline-session-count",
          label: "getOfflineSessionCount",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-offline-sessions",
          label: "getOfflineSessions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-optional-client-scopes",
          label: "getOptionalClientScopes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-optional-client-scope",
          label: "putOptionalClientScope",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-optional-client-scope",
          label: "deleteOptionalClientScope",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/post-client-push-revocation",
          label: "postClientPushRevocation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/post-registration-access-token",
          label: "postRegistrationAccessToken",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/get-service-account-user",
          label: "getServiceAccountUser",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-session-count",
          label: "getSessionCount",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-test-nodes-available",
          label: "getTestNodesAvailable",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-user-sessions",
          label: "getClientUserSessions",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Component",
      link: {
        type: "doc",
        id: "QIAM-API/component",
      },
      items: [
        {
          type: "doc",
          id: "QIAM-API/get-components",
          label: "getComponents",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-components",
          label: "postComponents",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/get-component",
          label: "getComponent",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-component",
          label: "putComponent",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-component",
          label: "deleteComponent",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-sub-component-types",
          label: "getSubComponentTypes",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Groups",
      link: {
        type: "doc",
        id: "QIAM-API/groups",
      },
      items: [
        {
          type: "doc",
          id: "QIAM-API/get-groups-by-realm",
          label: "getGroupsByRealm",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-groups",
          label: "postGroups",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/get-groups-count-by-realm",
          label: "getGroupsCountByRealm",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-group",
          label: "getGroup",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-group-by-realm-by-id",
          label: "putGroupByRealmById",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-group-by-realm-by-id",
          label: "deleteGroupByRealmById",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/post-children",
          label: "postChildren",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/get-group-management-permissions",
          label: "getGroupManagementPermissions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-group-management-permissions",
          label: "putGroupManagementPermissions",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/get-members",
          label: "getMembers",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Identity Providers",
      link: {
        type: "doc",
        id: "QIAM-API/identity-providers",
      },
      items: [
        {
          type: "doc",
          id: "QIAM-API/post-import-config",
          label: "postImportConfig",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/get-instances",
          label: "getInstances",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-instances",
          label: "postInstances",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/get-instance",
          label: "getInstance",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-instance",
          label: "putInstance",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-instance",
          label: "deleteInstance",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-export",
          label: "getExport",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-instance-management-permissions",
          label: "getInstanceManagementPermissions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-instance-management-permissions",
          label: "putInstanceManagementPermissions",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/get-mapper-types",
          label: "getMapperTypes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-mappers",
          label: "getMappers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-mappers",
          label: "postMappers",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/get-mapper",
          label: "getMapper",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-mapper",
          label: "putMapper",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-mapper",
          label: "deleteMapper",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-identity-provider-provider",
          label: "getIdentityProviderProvider",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Key",
      link: {
        type: "doc",
        id: "QIAM-API/key",
      },
      items: [
        {
          type: "doc",
          id: "QIAM-API/get-keys",
          label: "getKeys",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Protocol Mappers",
      link: {
        type: "doc",
        id: "QIAM-API/protocol-mappers",
      },
      items: [
        {
          type: "doc",
          id: "QIAM-API/get-client-scope-protocol-mappers-model",
          label: "getClientScopeProtocolMappersModel",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-client-scope-protocol-mappers-model",
          label: "putClientScopeProtocolMappersModel",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-client-scope-protocol-mappers-model",
          label: "deleteClientScopeProtocolMappersModel",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/post-client-scope-protocol-mappers-add-models",
          label: "postClientScopeProtocolMappersAddModels",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-scope-protocol-mappers-models",
          label: "getClientScopeProtocolMappersModels",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-client-scope-protocol-mappers-models",
          label: "postClientScopeProtocolMappersModels",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-scope-protocol-mappers-protocol",
          label: "getClientScopeProtocolMappersProtocol",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-template-protocol-mappers-model",
          label: "getClientTemplateProtocolMappersModel",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-client-template-protocol-mappers-model",
          label: "putClientTemplateProtocolMappersModel",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-client-template-protocol-mappers-model",
          label: "deleteClientTemplateProtocolMappersModel",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/post-client-template-protocol-mappers-add-models",
          label: "postClientTemplateProtocolMappersAddModels",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-template-protocol-mappers-models",
          label: "getClientTemplateProtocolMappersModels",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-client-template-protocol-mappers-models",
          label: "postClientTemplateProtocolMappersModels",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-template-protocol-mappers-protocol",
          label: "getClientTemplateProtocolMappersProtocol",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-protocol-mappers-model",
          label: "getClientProtocolMappersModel",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-client-protocol-mappers-model",
          label: "putClientProtocolMappersModel",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-client-protocol-mappers-model",
          label: "deleteClientProtocolMappersModel",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/post-client-protocol-mappers-add-models",
          label: "postClientProtocolMappersAddModels",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-protocol-mappers-models",
          label: "getClientProtocolMappersModels",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-client-protocol-mappers-models",
          label: "postClientProtocolMappersModels",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-protocol-mappers-protocol",
          label: "getClientProtocolMappersProtocol",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Realms Admin",
      link: {
        type: "doc",
        id: "QIAM-API/realms-admin",
      },
      items: [
        {
          type: "doc",
          id: "QIAM-API/get",
          label: "get",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post",
          label: "post",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/get-by-realm",
          label: "getByRealm",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-by-realm",
          label: "putByRealm",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-by-realm",
          label: "deleteByRealm",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-admin-events",
          label: "getAdminEvents",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-admin-events",
          label: "deleteAdminEvents",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/post-client-description-converter",
          label: "postClientDescriptionConverter",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/get-policies",
          label: "getPolicies",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-policies",
          label: "putPolicies",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/get-profiles",
          label: "getProfiles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-profiles",
          label: "putProfiles",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-session-stats",
          label: "getClientSessionStats",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-credential-registrators",
          label: "getCredentialRegistrators",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-default-default-client-scopes",
          label: "getDefaultDefaultClientScopes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-default-default-client-scope",
          label: "putDefaultDefaultClientScope",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-default-default-client-scope",
          label: "deleteDefaultDefaultClientScope",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-default-groups",
          label: "getDefaultGroups",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-default-group",
          label: "putDefaultGroup",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-default-group",
          label: "deleteDefaultGroup",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-default-optional-client-scopes",
          label: "getDefaultOptionalClientScopes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-default-optional-client-scope",
          label: "putDefaultOptionalClientScope",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-default-optional-client-scope",
          label: "deleteDefaultOptionalClientScope",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-events",
          label: "getEvents",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-events",
          label: "deleteEvents",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-events-config",
          label: "getEventsConfig",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-events-config",
          label: "putEventsConfig",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/get-group-by-path",
          label: "getGroupByPath",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-localization-by-realm",
          label: "getLocalizationByRealm",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-localization-by-realm-by-locale",
          label: "getLocalizationByRealmByLocale",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-localization",
          label: "postLocalization",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-localization-by-realm-by-locale",
          label: "deleteLocalizationByRealmByLocale",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-localization-by-realm-by-locale-by-key",
          label: "getLocalizationByRealmByLocaleByKey",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-localization",
          label: "putLocalization",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-localization-by-realm-by-locale-by-key",
          label: "deleteLocalizationByRealmByLocaleByKey",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/post-logout-all",
          label: "postLogoutAll",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/post-partial-export",
          label: "postPartialExport",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/post-partial-import",
          label: "postPartialImport",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/post-push-revocation-by-realm",
          label: "postPushRevocationByRealm",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-session",
          label: "deleteSession",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/post-test-smtp-connection",
          label: "postTestSmtpConnection",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/get-users-management-permissions",
          label: "getUsersManagementPermissions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-users-management-permissions",
          label: "putUsersManagementPermissions",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Role Mapper",
      link: {
        type: "doc",
        id: "QIAM-API/role-mapper",
      },
      items: [
        {
          type: "doc",
          id: "QIAM-API/get-group-role-mappings",
          label: "getGroupRoleMappings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-group-role-mappings-realm",
          label: "getGroupRoleMappingsRealm",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-group-role-mappings-realm",
          label: "postGroupRoleMappingsRealm",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-group-role-mappings-realm",
          label: "deleteGroupRoleMappingsRealm",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-group-role-mappings-realm-available",
          label: "getGroupRoleMappingsRealmAvailable",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-group-role-mappings-realm-composite",
          label: "getGroupRoleMappingsRealmComposite",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-user-role-mappings",
          label: "getUserRoleMappings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-user-role-mappings-realm",
          label: "getUserRoleMappingsRealm",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-user-role-mappings-realm",
          label: "postUserRoleMappingsRealm",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-user-role-mappings-realm",
          label: "deleteUserRoleMappingsRealm",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-user-role-mappings-realm-available",
          label: "getUserRoleMappingsRealmAvailable",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-user-role-mappings-realm-composite",
          label: "getUserRoleMappingsRealmComposite",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Roles",
      link: {
        type: "doc",
        id: "QIAM-API/roles",
      },
      items: [
        {
          type: "doc",
          id: "QIAM-API/get-client-roles",
          label: "getClientRoles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-client-roles",
          label: "postClientRoles",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-role",
          label: "getClientRole",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-client-role",
          label: "putClientRole",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-client-role",
          label: "deleteClientRole",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-role-composites",
          label: "getClientRoleComposites",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-client-role-composites",
          label: "postClientRoleComposites",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-client-role-composites",
          label: "deleteClientRoleComposites",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-role-composites-client",
          label: "getClientRoleCompositesClient",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-role-composites-realm",
          label: "getClientRoleCompositesRealm",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-role-groups",
          label: "getClientRoleGroups",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-role-management-permissions",
          label: "getClientRoleManagementPermissions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-client-role-management-permissions",
          label: "putClientRoleManagementPermissions",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-role-users",
          label: "getClientRoleUsers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-roles-by-realm",
          label: "getRolesByRealm",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-roles-by-realm",
          label: "postRolesByRealm",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/get-role-by-realm-by-role-name",
          label: "getRoleByRealmByRoleName",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-role-by-realm-by-role-name",
          label: "putRoleByRealmByRoleName",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-role-by-realm-by-role-name",
          label: "deleteRoleByRealmByRoleName",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-role-composites-by-realm-by-role-name",
          label: "getRoleCompositesByRealmByRoleName",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-role-composites-by-realm-by-role-name",
          label: "postRoleCompositesByRealmByRoleName",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-role-composites-by-realm-by-role-name",
          label: "deleteRoleCompositesByRealmByRoleName",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-role-composites-client-by-realm-by-role-name-by-client-uuid",
          label: "getRoleCompositesClientByRealmByRoleNameByClientUuid",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-role-composites-realm-by-realm-by-role-name",
          label: "getRoleCompositesRealmByRealmByRoleName",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-role-groups-by-realm-by-role-name",
          label: "getRoleGroupsByRealmByRoleName",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-role-management-permissions-by-realm-by-role-name",
          label: "getRoleManagementPermissionsByRealmByRoleName",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-role-management-permissions-by-realm-by-role-name",
          label: "putRoleManagementPermissionsByRealmByRoleName",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/get-role-users-by-realm-by-role-name",
          label: "getRoleUsersByRealmByRoleName",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Roles (by ID)",
      link: {
        type: "doc",
        id: "QIAM-API/roles-by-id",
      },
      items: [
        {
          type: "doc",
          id: "QIAM-API/get-roles-by-id",
          label: "getRolesById",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-roles-by-id",
          label: "putRolesById",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-roles-by-id",
          label: "deleteRolesById",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-roles-by-id-composites",
          label: "getRolesByIdComposites",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-roles-by-id-composites",
          label: "postRolesByIdComposites",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-roles-by-id-composites",
          label: "deleteRolesByIdComposites",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-roles-by-id-composites-client",
          label: "getRolesByIdCompositesClient",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-roles-by-id-composites-realm",
          label: "getRolesByIdCompositesRealm",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-roles-by-id-management-permissions",
          label: "getRolesByIdManagementPermissions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-roles-by-id-management-permissions",
          label: "putRolesByIdManagementPermissions",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Scope Mappings",
      link: {
        type: "doc",
        id: "QIAM-API/scope-mappings",
      },
      items: [
        {
          type: "doc",
          id: "QIAM-API/get-client-scope-scope-mappings",
          label: "getClientScopeScopeMappings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-scope-scope-mappings-client",
          label: "getClientScopeScopeMappingsClient",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-client-scope-scope-mappings-client",
          label: "postClientScopeScopeMappingsClient",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-client-scope-scope-mappings-client",
          label: "deleteClientScopeScopeMappingsClient",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-scope-scope-mappings-client-available",
          label: "getClientScopeScopeMappingsClientAvailable",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-scope-scope-mappings-client-composite",
          label: "getClientScopeScopeMappingsClientComposite",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-scope-scope-mappings-realm",
          label: "getClientScopeScopeMappingsRealm",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-client-scope-scope-mappings-realm",
          label: "postClientScopeScopeMappingsRealm",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-client-scope-scope-mappings-realm",
          label: "deleteClientScopeScopeMappingsRealm",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-scope-scope-mappings-realm-available",
          label: "getClientScopeScopeMappingsRealmAvailable",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-scope-scope-mappings-realm-composite",
          label: "getClientScopeScopeMappingsRealmComposite",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-template-scope-mappings",
          label: "getClientTemplateScopeMappings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-template-scope-mappings-client",
          label: "getClientTemplateScopeMappingsClient",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-client-template-scope-mappings-client",
          label: "postClientTemplateScopeMappingsClient",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-client-template-scope-mappings-client",
          label: "deleteClientTemplateScopeMappingsClient",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-template-scope-mappings-client-available",
          label: "getClientTemplateScopeMappingsClientAvailable",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-template-scope-mappings-client-composite",
          label: "getClientTemplateScopeMappingsClientComposite",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-template-scope-mappings-realm",
          label: "getClientTemplateScopeMappingsRealm",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-client-template-scope-mappings-realm",
          label: "postClientTemplateScopeMappingsRealm",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-client-template-scope-mappings-realm",
          label: "deleteClientTemplateScopeMappingsRealm",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-template-scope-mappings-realm-available",
          label: "getClientTemplateScopeMappingsRealmAvailable",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-template-scope-mappings-realm-composite",
          label: "getClientTemplateScopeMappingsRealmComposite",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-scope-mappings",
          label: "getClientScopeMappings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-scope-mappings-client",
          label: "getClientScopeMappingsClient",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-client-scope-mappings-client",
          label: "postClientScopeMappingsClient",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-client-scope-mappings-client",
          label: "deleteClientScopeMappingsClient",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-scope-mappings-client-available",
          label: "getClientScopeMappingsClientAvailable",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-scope-mappings-client-composite",
          label: "getClientScopeMappingsClientComposite",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-scope-mappings-realm",
          label: "getClientScopeMappingsRealm",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-client-scope-mappings-realm",
          label: "postClientScopeMappingsRealm",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-client-scope-mappings-realm",
          label: "deleteClientScopeMappingsRealm",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-scope-mappings-realm-available",
          label: "getClientScopeMappingsRealmAvailable",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-client-scope-mappings-realm-composite",
          label: "getClientScopeMappingsRealmComposite",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Users",
      link: {
        type: "doc",
        id: "QIAM-API/users",
      },
      items: [
        {
          type: "doc",
          id: "QIAM-API/get-users-by-realm",
          label: "getUsersByRealm",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-users",
          label: "postUsers",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/get-users-count",
          label: "getUsersCount",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-profile",
          label: "getProfile",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-profile",
          label: "putProfile",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/get-user-by-realm-by-id",
          label: "getUserByRealmById",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-user",
          label: "putUser",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-user-by-realm-by-id",
          label: "deleteUserByRealmById",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-configured-user-storage-credential-types",
          label: "getConfiguredUserStorageCredentialTypes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-consents",
          label: "getConsents",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-consent",
          label: "deleteConsent",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-credentials",
          label: "getCredentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-credential",
          label: "deleteCredential",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/post-move-after",
          label: "postMoveAfter",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/post-move-to-first",
          label: "postMoveToFirst",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/put-user-label",
          label: "putUserLabel",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/put-disable-credential-types",
          label: "putDisableCredentialTypes",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/put-execute-actions-email",
          label: "putExecuteActionsEmail",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/get-federated-identity",
          label: "getFederatedIdentity",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/post-federated-identity",
          label: "postFederatedIdentity",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-federated-identity",
          label: "deleteFederatedIdentity",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/get-user-groups",
          label: "getUserGroups",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/get-user-groups-count",
          label: "getUserGroupsCount",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-user-group",
          label: "putUserGroup",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/delete-user-group",
          label: "deleteUserGroup",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "QIAM-API/post-impersonation",
          label: "postImpersonation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/post-logout",
          label: "postLogout",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "QIAM-API/get-offline-session",
          label: "getOfflineSession",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "QIAM-API/put-reset-password",
          label: "putResetPassword",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/put-reset-password-email",
          label: "putResetPasswordEmail",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/put-send-verify-email",
          label: "putSendVerifyEmail",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "QIAM-API/get-sessions",
          label: "getSessions",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "QIAM-API/schemas/access",
          label: "Access",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/accesstoken",
          label: "AccessToken",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/addressclaimset",
          label: "AddressClaimSet",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/applicationrepresentation",
          label: "ApplicationRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/applicationrepresentationclaims",
          label: "ApplicationRepresentationClaims",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/authenticationexecutionexportrepresentation",
          label: "AuthenticationExecutionExportRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/authenticationexecutioninforepresentation",
          label: "AuthenticationExecutionInfoRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/authenticationexecutionrepresentation",
          label: "AuthenticationExecutionRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/authenticationflowrepresentation",
          label: "AuthenticationFlowRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/authenticatorconfiginforepresentation",
          label: "AuthenticatorConfigInfoRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/authenticatorconfigrepresentation",
          label: "AuthenticatorConfigRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/authorization",
          label: "Authorization",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/certconf",
          label: "CertConf",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/certificaterepresentation",
          label: "CertificateRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/claimrepresentation",
          label: "ClaimRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/clientinitialaccesscreatepresentation",
          label: "ClientInitialAccessCreatePresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/clientinitialaccesspresentation",
          label: "ClientInitialAccessPresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/clientmappingsrepresentation",
          label: "ClientMappingsRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/clientpoliciesrepresentation",
          label: "ClientPoliciesRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/clientpolicyconditionrepresentation",
          label: "ClientPolicyConditionRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/clientpolicyexecutorrepresentation",
          label: "ClientPolicyExecutorRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/clientpolicyrepresentation",
          label: "ClientPolicyRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/clientprofilerepresentation",
          label: "ClientProfileRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/clientprofilesrepresentation",
          label: "ClientProfilesRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/clientrepresentation",
          label: "ClientRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/clientscoperepresentation",
          label: "ClientScopeRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/clienttemplaterepresentation",
          label: "ClientTemplateRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/componentexportrepresentation",
          label: "ComponentExportRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/componentrepresentation",
          label: "ComponentRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/composites",
          label: "Composites",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/configpropertyrepresentation",
          label: "ConfigPropertyRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/credentialrepresentation",
          label: "CredentialRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/decisionstrategy",
          label: "DecisionStrategy",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/enforcementmode",
          label: "EnforcementMode",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/federatedidentityrepresentation",
          label: "FederatedIdentityRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/globalrequestresult",
          label: "GlobalRequestResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/grouprepresentation",
          label: "GroupRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/idtoken",
          label: "IDToken",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/identityprovidermapperrepresentation",
          label: "IdentityProviderMapperRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/identityprovidermappertyperepresentation",
          label: "IdentityProviderMapperTypeRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/identityproviderrepresentation",
          label: "IdentityProviderRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/installationadapterconfig",
          label: "InstallationAdapterConfig",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/keymetadatarepresentation",
          label: "KeyMetadataRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/keystoreconfig",
          label: "KeyStoreConfig",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/keyuse",
          label: "KeyUse",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/keysmetadatarepresentation",
          label: "KeysMetadataRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/logic",
          label: "Logic",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/managementpermissionreference",
          label: "ManagementPermissionReference",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/mappingsrepresentation",
          label: "MappingsRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/methodconfig",
          label: "MethodConfig",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/oauthclientrepresentation",
          label: "OAuthClientRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/pathcacheconfig",
          label: "PathCacheConfig",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/pathconfig",
          label: "PathConfig",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/permission",
          label: "Permission",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/policyenforcementmode",
          label: "PolicyEnforcementMode",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/policyenforcerconfig",
          label: "PolicyEnforcerConfig",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/policyrepresentation",
          label: "PolicyRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/protocolmapperrepresentation",
          label: "ProtocolMapperRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/publishedrealmrepresentation",
          label: "PublishedRealmRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/realmeventsconfigrepresentation",
          label: "RealmEventsConfigRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/realmrepresentation",
          label: "RealmRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/requiredactionproviderrepresentation",
          label: "RequiredActionProviderRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/resourceownerrepresentation",
          label: "ResourceOwnerRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/resourcerepresentation",
          label: "ResourceRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/resourcerepresentationowner",
          label: "ResourceRepresentationOwner",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/resourceserverrepresentation",
          label: "ResourceServerRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/rolerepresentation",
          label: "RoleRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/rolesrepresentation",
          label: "RolesRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/scopeenforcementmode",
          label: "ScopeEnforcementMode",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/scopemappingrepresentation",
          label: "ScopeMappingRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/scoperepresentation",
          label: "ScopeRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/sociallinkrepresentation",
          label: "SocialLinkRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/userconsentrepresentation",
          label: "UserConsentRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/userfederationmapperrepresentation",
          label: "UserFederationMapperRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/userfederationproviderrepresentation",
          label: "UserFederationProviderRepresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "QIAM-API/schemas/userrepresentation",
          label: "UserRepresentation",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
